t = (" Desafio 26 ")
print(f"{t:=^20}")
nome = str(input("Digite uma frase: ")).strip().lower()
num = nome.count("a")
pos = nome.find("a")
ult = nome.rfind("a")
print(f"Aparecem {num} vezes a letra A na sua frase.")
print(f"A letra A aparece a primeira vez na posição {pos + 1}.")
print(f"A última letra A aparece na {ult + 1} posição.")