t = (" Desafio 22 ")
print(f"{t:=^20}")
nome = str(input("Digite seu nome completo: ")).strip()
print(f"Seu nome maiúsculo é {nome.upper()}")
print(f"Seu nome minúsculo é {nome.lower()}")
letras = (len(nome)) - (nome.count(" "))
print(f"Seu nome tem {letras} letras")
div = nome.split()
print(f"Seu primeiro nome é {div[0]} e ele tem {len(div[0])} letras.")
primeiro = len(nome[0:nome.find(" ")])
print(f"Seu primeiro nome tem {primeiro} letras.")