print('===== Desafio 02 =====')
dia = input('Qual o dia que você nasceu? ')
mes = input('Qual o mês que você nasceu? ')
ano = input('Qual o ano que você nasceu? ')
print('Você nasceu em \033[7m', dia, '\033[m de \033[7m', mes, '\033[m de \033[7m', ano, '\033[m, correto?')
